# Generated by Django 5.2.4 on 2025-09-21 18:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of the expense')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Original amount', max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('LBP', 'Lebanese Lira'), ('SAR', 'Saudi Riyal')], default='USD', max_length=3)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('consumption_type', models.CharField(choices=[('market', 'Market'), ('transport', 'Transport'), ('food', 'Food'), ('other', 'Other')], default='market', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (used to detect timezone)', max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(default='active', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consumptions', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_consumptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
    ]
