# Generated by Django 5.2.4 on 2025-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='consumption_type',
            field=models.CharField(choices=[('market', 'Market'), ('food', 'Food'), ('other', 'Other')], default='market', max_length=20),
        ),
    ]
