# Generated by Django 5.2.4 on 2025-07-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_consumption_consumption_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
