# Generated by Django 5.2.4 on 2025-07-15 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_consumption_options_consumption_amount_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the expense'),
        ),
    ]
